// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlldfecwhjxsdtzftbiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsbGRmZWN3aGp4c2R0emZ0Yml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzgyMTAsImV4cCI6MjA2NzMxNDIxMH0.qBaMFxY6xseDZ12E26a1Dc5Nc6cUsIyrMhibrbmnSu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});